// top 50 stations in India from chat gpt
export const stations = [
    { code: "NDLS", name: "New Delhi" },
    { code: "BCT", name: "Mumbai Central" },
    { code: "CSTM", name: "Mumbai CST" },
    { code: "HWH", name: "Howrah Junction" },
    { code: "MAS", name: "Chennai Central" },
    { code: "SBC", name: "Bangalore City" },
    { code: "PNBE", name: "Patna Junction" },
    { code: "LKO", name: "Lucknow Junction" },
    { code: "HYB", name: "Hyderabad Deccan" },
    { code: "GWL", name: "Gwalior" },
    { code: "BPL", name: "Bhopal Junction" },
    { code: "CNB", name: "Kanpur Central" },
    { code: "ALD", name: "Prayagraj Junction" },
    { code: "BBS", name: "Bhubaneswar" },
    { code: "KOAA", name: "Kolkata" },
    { code: "GKP", name: "Gorakhpur" },
    { code: "PUNE", name: "Pune Junction" },
    { code: "VSKP", name: "Visakhapatnam" },
    { code: "JAIP", name: "Jaipur" },
    { code: "JP", name: "Jodhpur" },
    { code: "AGC", name: "Agra Cantonment" },
    { code: "BKN", name: "Bikaner" },
    { code: "ASR", name: "Amritsar" },
    { code: "GZB", name: "Ghaziabad" },
    { code: "CBE", name: "Coimbatore" },
    { code: "TVC", name: "Trivandrum" },
    { code: "KGP", name: "Kharagpur" },
    { code: "RNC", name: "Ranchi" },
    { code: "JAT", name: "Jammu Tawi" },
    { code: "ADI", name: "Ahmedabad" },
    { code: "RJT", name: "Rajkot" },
    { code: "DLI", name: "Old Delhi" },
    { code: "ET", name: "Itarsi" },
    { code: "KYN", name: "Kalyan Junction" },
    { code: "NGP", name: "Nagpur" },
    { code: "DBG", name: "Darbhanga" },
    { code: "RMM", name: "Rameswaram" },
    { code: "MDU", name: "Madurai" },
    { code: "UBL", name: "Hubballi" },
    { code: "SUR", name: "Solapur" },
    { code: "BAM", name: "Brahmapur" },
    { code: "TATA", name: "Tatanagar" },
    { code: "ST", name: "Surat" },
    { code: "VAPI", name: "Vapi" },
    { code: "NZM", name: "Hazrat Nizamuddin" },
    { code: "MTJ", name: "Mathura Junction" },
    { code: "MFP", name: "Muzaffarpur" },
    { code: "DNR", name: "Danapur" },
    { code: "SRE", name: "Saharanpur" }
  ];